services:
  front-end-prod:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 8080:80
  back-end-prod:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/data:/usr/src/app/data
    ports:
      - 3001:3001
